## reference: http://docs.travis-ci.com/user/languages/r/

language: r
r:
  - oldrel
  - release
r_packages:
  - covr
  - testthat

after_success:
  - Rscript -e 'library(covr); codecov()'

