# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

px <- function(phi, Z) {
    .Call(`_CutBase_px`, phi, Z)
}

py <- function(Y, theta, phi) {
    .Call(`_CutBase_py`, Y, theta, phi)
}

